version: "3"

services:
  db:
    image: mongo:latest
    volumes:
      - sdfeedbackdb:/data/db
    networks:
      - sdfeedback
  
  server:
    build: ./server
    networks:
      - sdfeedback
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules/
    ports:
      - 5060:5060
    depends_on:
      - db
    command: ["nodemon", "index.js"]
  
networks:
  sdfeedback:
volumes:
  sdfeedbackdb: